import { NextComponentType, NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/navigation'
import { useState } from 'react'


const Home: NextPage = () => {

  const router = useRouter() 

const [sub, setSoma] = useState<number>(0)

const Sub = (): number => {
  setSoma(sub - 1)
  return sub
}

const RotaSomar = () => {
router.push("/")
}
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     <button onClick={() => Sub()}>menos</button>
     <p>{sub}</p>
     <button onClick={() => RotaSomar()}>Voltar</button>
      </main>
    </>
  )
}


export default Home